# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: AppBundle:User
                property: login
                # if you're using multiple entity managers
                # manager_name: customer


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            form_login:
                login_path: login
                check_path: login
                default_target_path: /

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

            logout:
                path:   /logout
                target: /

    role_hierarchy:
          ROLE_SUPERVISOR: ROLE_USER
          ROLE_MASTER: ROLE_SUPERVISOR
          ROLE_SUBADMIN: ROLE_MASTER
          ROLE_ADMIN: ROLE_SUBADMIN
