<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerIwjpnxo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwjpnxo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIwjpnxo.legacy');
=======
if (\class_exists(\Container3xiupuk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3xiupuk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3xiupuk.legacy');
>>>>>>> a40de895517d7b604e92cb8c6d2bc51f50df4c71

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerIwjpnxo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIwjpnxo\appDevDebugProjectContainer();
=======
    \class_alias(\Container3xiupuk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3xiupuk\appDevDebugProjectContainer();
>>>>>>> a40de895517d7b604e92cb8c6d2bc51f50df4c71
