<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwjpnxo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwjpnxo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIwjpnxo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIwjpnxo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIwjpnxo\appDevDebugProjectContainer();
